#!/usr/bin/env php
<?php
namespace think;

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 应用初始化
try {
    (new App())->console->run();
} catch (\Exception $e) {
    exit($e->getMessage());
}